package cn.misection.cvac.codegen;

import cn.misection.cvac.codegen.ast.CodeGenAst;
import cn.misection.cvac.codegen.ast.CodeGenVisitor;

import java.io.FileNotFoundException;
import java.io.IOException;

/**
 * Created by Mengxu on 2017/1/18.
 */
public class ByteCodeGenerator implements CodeGenVisitor
{
    private java.io.BufferedWriter writer;

    private void writeln(String s)
    {
        write(String.format("%s\n", s));
    }

    private void write(String s)
    {
        try
        {
            this.writer.write(s);
        } catch (IOException e)
        {
            e.printStackTrace();
            System.exit(1);
        }
    }

    private void iwriteln(String s)
    {
        write(String.format("    %s\n", s));
    }

    @Override
    public void visit(CodeGenAst.Type.ClassType t)
    {
        this.write(String.format("L%s;", t.getLiteral()));
    }

    @Override
    public void visit(CodeGenAst.Type.Int t)
    {
        this.write("I");
    }

    @Override
    public void visit(CodeGenAst.Dec.DecSingle d)
    {
        this.writeln(";Error: you are accessing the dec single instance.");
    }

    @Override
    public void visit(CodeGenAst.Stm.Aload s)
    {
        this.iwriteln(String.format("aload %d", s.getIndex()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Areturn s)
    {
        this.iwriteln("areturn");
    }

    @Override
    public void visit(CodeGenAst.Stm.Astore s)
    {
        this.iwriteln(String.format("astore %d", s.getIndex()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Goto s)
    {
        this.iwriteln(String.format("goto %s", s.getLabel().toString()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Getfield s)
    {
        this.iwriteln(String.format("getfield %s %s", s.getFieldSpec(), s.descriptor));
    }

    @Override
    public void visit(CodeGenAst.Stm.Iadd s)
    {
        this.iwriteln("iadd");
    }

    @Override
    public void visit(CodeGenAst.Stm.Ificmplt s)
    {
        this.iwriteln(String.format("if_icmplt %s", s.getLabel().toString()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Iload s)
    {
        this.iwriteln(String.format("iload %d", s.getIndex()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Imul s)
    {
        this.iwriteln("imul");
    }

    @Override
    public void visit(CodeGenAst.Stm.Invokevirtual s)
    {
        this.write(String.format("    invokevirtual %s/%s(", s.c, s.f));
        s.at.forEach(this::visit);
        this.write(")");
        this.visit(s.rt);
        this.writeln("");
    }

    @Override
    public void visit(CodeGenAst.Stm.Ireturn s)
    {
        this.iwriteln("ireturn");
    }

    @Override
    public void visit(CodeGenAst.Stm.Istore s)
    {
        this.iwriteln(String.format("istore %d", s.getIndex()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Isub s)
    {
        this.iwriteln("isub");
    }

    @Override
    public void visit(CodeGenAst.Stm.LabelJ s)
    {
        this.writeln(String.format("%s:", s.getLabel().toString()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Ldc s)
    {
        this.iwriteln(String.format("ldc %d", s.getInteg()));
    }

    @Override
    public void visit(CodeGenAst.Stm.New s)
    {
        this.iwriteln(String.format("new %s", s.getClas()));
        this.iwriteln("dup");
        this.iwriteln(String.format("invokespecial %s/<init>()V", s.getClas()));
    }

    @Override
    public void visit(CodeGenAst.Stm.Write s)
    {
        this.iwriteln("getstatic java/lang/System/out Ljava/io/PrintStream;");
        this.iwriteln("swap");
        // TODO 封装常量字段, 同时把println变成print;
        this.iwriteln("invokevirtual java/io/PrintStream/println(I)V");
    }

    @Override
    public void visit(CodeGenAst.Stm.Putfield s)
    {
        this.iwriteln(String.format("putfield %s %s", s.getFieldSpec(), s.descriptor));
    }

    @Override
    public void visit(CodeGenAst.Method.MethodSingle m)
    {
        this.write(String.format(".method public %s(", m.getId()));
        m.getFormals().forEach(f -> this.visit(f.getType()));
        this.write(")");
        this.visit(m.getRetType());
        this.writeln("");
        this.writeln(".limit stack 4096");
        this.writeln(String.format(".limit locals %d", m.getIndex() + 1));

        m.getStms().forEach(this::visit);
        this.writeln(".end method");
    }

    @Override
    public void visit(CodeGenAst.Class.ClassSingle c)
    {
        try
        {
            // FIXME 路劲;
            this.writer = new java.io.BufferedWriter(new java.io.OutputStreamWriter(
                    new java.io.FileOutputStream(String.format("%s.il", c.getLiteral()))));
        } catch (FileNotFoundException e)
        {
            e.printStackTrace();
            System.exit(1);
        }

        this.writeln("; This file is automatically generated by the compiler");
        this.writeln("; Do Not Modify!\n");

        this.writeln(String.format(".class public %s", c.getLiteral()));
        if (c.getBase() == null)
            this.writeln(".super java/lang/Object");
        else this.writeln(String.format(".super %s", c.getBase()));

        c.getFields().forEach(f ->
        {
            this.write(String.format(".field public %s ", f.getLiteral()));
            this.visit(f.getType());
            this.writeln("");
        });

        this.writeln(".method public <init>()V");
        this.iwriteln("aload 0");
        if (c.getBase() == null)
            this.iwriteln("invokespecial java/lang/Object/<init>()V");
        else this.iwriteln(String.format("invokespecial %s/<init>()V", c.getBase()));
        this.iwriteln("return");
        this.writeln(".end method");
        c.getMethods().forEach(this::visit);

        try
        {
            this.writer.close();
        } catch (IOException e)
        {
            e.printStackTrace();
            System.exit(1);
        }
    }

    @Override
    public void visit(CodeGenAst.MainClass.MainClassSingle c)
    {
        try
        {
            this.writer = new java.io.BufferedWriter(new java.io.OutputStreamWriter(
                    new java.io.FileOutputStream(String.format("%s.il", c.getLiteral()))));
        } catch (Exception e)
        {
            e.printStackTrace();
            System.exit(1);
        }

        this.writeln("; This file is automatically generated by the compiler");
        this.writeln("; Do Not Modify!\n");

        this.writeln(String.format(".class public %s", c.getLiteral()));
        this.writeln(".super java/lang/Object");
        this.writeln(".method public static main([Ljava/lang/String;)V");
        this.writeln(".limit stack 4096");
        this.writeln(".limit locals 2");
        c.getStms().forEach(this::visit);
        this.iwriteln("return");
        this.writeln(".end method");

        try
        {
            this.writer.close();
        } catch (IOException e)
        {
            e.printStackTrace();
            System.exit(1);
        }
    }

    @Override
    public void visit(CodeGenAst.Program.ProgramSingle p)
    {
        this.visit(p.mainClass);
        p.classes.forEach(this::visit);
    }
}
